import {useEffect,useState} from 'react';
import {MapPin,ChevronDown,ShoppingBag,Heart,UserRound,LogOut,UtensilsCrossed} from 'lucide-react';
import {api} from './api';
import Catalog,{RestaurantMenu} from './Catalog';
import AuthModal from './AuthModal';
export default function App(){
 const [restaurants,setRestaurants]=useState([]),[cities,setCities]=useState([]),[user,setUser]=useState(null),[auth,setAuth]=useState(false),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[city,setCity]=useState('Prishtinë'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[notice,setNotice]=useState('');
 async function load(){setLoading(true);setError('');try{const [r,c]=await Promise.all([api('restaurants'),api('cities')]);setRestaurants(r.data);setCities(c.data)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load();api('user').then(r=>setUser(r.user)).catch(e=>{if(e.status!==401)setError(e.message)})},[]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(id)},[notice]);
 return <><header className="site-header"><div className="header-inner"><button className="brand" onClick={()=>setSelected(null)}><span className="brand-icon"><UtensilsCrossed size={22}/></span>shija<span className="brand-dot">.</span></button><div className="header-divider"/><label className="location"><MapPin size={21}/><span><small>DELIVERING TO</small><select aria-label="Delivery city" value={city} onChange={e=>setCity(e.target.value)}>{cities.map(c=><option key={c}>{c}</option>)}</select></span><ChevronDown size={14}/></label><nav><button className="nav-link" onClick={()=>{setSelected(null);document.getElementById('restaurants')?.scrollIntoView({behavior:'smooth'})}}>Explore</button><button className="nav-link" onClick={()=>user?setNotice('Your favorites will appear here soon.'):setAuth(true)}><Heart size={18}/><span>Favorites</span></button>{user?<><button className="nav-link" onClick={()=>setNotice(`Welcome, ${user.name}`)}><UserRound size={17}/>{user.name.split(' ')[0]}</button><button className="icon" aria-label="Sign out" onClick={async()=>{await api('logout',{method:'POST'});setUser(null)}}><LogOut size={18}/></button></>:<button className="login-button" onClick={()=>setAuth(true)}><UserRound size={17}/>Sign in</button>}<button className="cart-button" onClick={()=>setNotice('Choose a restaurant to start your order.')}><ShoppingBag size={18}/><span>Cart</span><b>0</b></button></nav></div></header><main className="container">{loading?<div className="empty loading">Setting the table…</div>:error?<div className="empty"><h2>We couldn’t load the menu.</h2><p>{error}</p><button className="primary" onClick={load}>Try again</button></div>:selected?<RestaurantMenu restaurant={selected} onBack={()=>setSelected(null)} onAdd={()=>setNotice('Cart ordering is coming in the next milestone.')} onFavorite={()=>setAuth(true)} isFavorite={()=>false}/>:<Catalog restaurants={restaurants} query={query} setQuery={setQuery} onSelect={r=>{setSelected(r);window.scrollTo(0,0)}} onFavorite={()=>setAuth(true)} isFavorite={()=>false}/>}</main><footer className="footer"><div className="container footer-inner"><div><span className="brand">shija<span className="brand-dot">.</span></span><p>A little joy, delivered.</p></div><p>Made for hungry people in Kosovo. <span>♥</span></p><span>Fresh food. Local love.</span></div></footer>{auth&&<AuthModal cities={cities} onClose={()=>setAuth(false)} onSuccess={u=>{setUser(u);setCity(u.city||city);setAuth(false);setNotice(`Welcome, ${u.name}!`)}}/>}{notice&&<div className="toast" role="status">{notice}</div>}</>
}
